/* Generated By:JavaCC: Do not edit this line. BrCompilerTreeConstants.java Version 7.0.12 */
package parser;

public interface BrCompilerTreeConstants
{
  public int JJTMAIN = 0;
  public int JJTBLOCO = 1;
  public int JJTCOMANDO = 2;
  public int JJTCOMANDOIDENTIFICADOR = 3;
  public int JJTCOMANDOIDENTIFICADORSUFIXO = 4;
  public int JJTSUFIXOEXPRESSAO = 5;
  public int JJTDECLARAVARIAVEL = 6;
  public int JJTTIPODADO = 7;
  public int JJTLISTAIDENTIFICADORES = 8;
  public int JJTLISTAEXPRESSOES = 9;
  public int JJTEXPRESSAO = 10;
  public int JJTFATOR = 11;
  public int JJTTERMO = 12;
  public int JJTTERMOIDENTIFICADORSUFIXO = 13;
  public int JJTOPERADORLOGICO = 14;
  public int JJTEXPRESSAOLOGICA = 15;
  public int JJTEXPRESSAOCONDICIONAL = 16;
  public int JJTCONDICAO = 17;
  public int JJTPRINT = 18;
  public int JJTSCAN = 19;
  public int JJTWHILELOOP = 20;
  public int JJTFORLOOP = 21;
  public int JJTATRIBUICAOFOR = 22;
  public int JJTDECLARAFUNCAO = 23;
  public int JJTLISTAPARAMETROS = 24;
  public int JJTPARAMETRO = 25;
  public int JJTRETORNO = 26;
  public int JJTTIPOLISTA = 27;
  public int JJTINICIALIZACAOLISTA = 28;
  public int JJTTIPOPILHA = 29;


  public String[] jjtNodeName = {
    "main",
    "bloco",
    "comando",
    "comandoIdentificador",
    "comandoIdentificadorSufixo",
    "sufixoExpressao",
    "declaraVariavel",
    "tipoDado",
    "ListaIdentificadores",
    "ListaExpressoes",
    "Expressao",
    "fator",
    "termo",
    "termoIdentificadorSufixo",
    "operadorLogico",
    "expressaoLogica",
    "expressaoCondicional",
    "condicao",
    "print",
    "scan",
    "whileLoop",
    "forLoop",
    "atribuicaoFor",
    "declaraFuncao",
    "listaParametros",
    "parametro",
    "retorno",
    "tipoLista",
    "inicializacaoLista",
    "tipoPilha",
  };
}
/* JavaCC - OriginalChecksum=db81249b8f650265ccf59f85a56d918c (do not edit this line) */
