/* BrCompiler.java */
/* Generated By:JJTree&JavaCC: Do not edit this line. BrCompiler.java */
package parser;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.StringReader;
import recovery.RecoverySet;
import recovery.ParseEOFException;
import recovery.Follow;
import recovery.ErrorManager;
import recovery.DelimiterBalancer;

public class BrCompiler/*@bgen(jjtree)*/implements BrCompilerTreeConstants, BrCompilerConstants {/*@bgen(jjtree)*/
  protected static JJTBrCompilerState jjtree = new JJTBrCompilerState();private static boolean parserInitialized = false;
  static DelimiterBalancer delimiterBalancer = new DelimiterBalancer();
  static DelimiterBalancer.UnbalancedDelimiterException balanceException = null;

  public static String obterTokenPortugues(int tipoToken) {
    switch(tipoToken) {
      case INICIOPROG: return "gambiarra";
      case ABREBLOCO: return "abre-te-sesamo";
      case FECHABLOCO: return "fecha-te-sesamo";
      case INT: return "stonks";
      case FLOAT: return "fiado";
      case STRING: return "textao";
      case BOOL: return "eh-migue";
      case TRUE: return "sim";
      case FALSE: return "nao";
      case ATRIBUICAO: return "receba";
      case FIMESTRUTURA: return "br";
      case CONDICIONAL: return "sepa";
      case SENAO: return "da-teus-pulo";
      case ABRIREXP: return "[";
      case FECHAREXP: return "]";
      case ABRIRFUNC: return "(";
      case FECHARFUNC: return ")";
      case PRINT: return "printa";
      case SCAN: return "papa-entrada";
      case FOR: return "pet";
      case WHILE: return "repet";
      case FUNCAO: return "vai-filhao";
      case RETURN: return "devolva";
      case SEPARADOR: return ";";
      case SOMA: return "+";
      case SUBTRACAO: return "-";
      case MULTIPLICACAO: return "*";
      case DIVISAO: return "/";
      case OPMAIOR: return ">";
      case OPIGUAL: return "==";
      case OPMENOR: return "<";
      case OPMAIORIGUAL: return ">=";
      case OPMENORIGUAL: return "<=";
      case OPDIF: return "!=";
      case OPAND: return "&&";
      case OPOR: return "|";
      case IDENTIFICADOR: return "identificador";
      case CONSTANTE_INT: return "numero inteiro";
      case CONSTANTE_FLOAT: return "numero decimal";
      case LITERAL_STRING: return "texto";
      case VIRGULA: return "virgula (,)";
      case LISTA: return "tropa-do-gordao";
      case ADICIONAR: return "recrutar";
      case REMOVER: return "expulsar";
      case TAMANHO: return "tamanho";
      case PILHA: return "sanduiche-iche";
      case EMPILHAR: return "montar-sanduba";
      case DESEMPILHAR: return "comer-sanduba";
      case TOPO: return "olho-gordo";
      case PILHA_VAZIA: return "farelo";
      default: return "token desconhecido";
    }
  }

  public static String handleParseError(ParseException e) {
    StringBuilder resultado = new StringBuilder();

    if (e.expectedTokenSequences != null && e.expectedTokenSequences.length > 0) {
        boolean temFechabloco = false;

        for (int[] sequence : e.expectedTokenSequences) {
            for (int tokenType : sequence) {
                if (tokenType == FECHABLOCO) {
                    temFechabloco = true;
                    break;
                }
            }
            if (temFechabloco) break;
        }

        if (temFechabloco) {
            resultado.append("ERRO DE SINTAXE: Bloco nao fechado\n");
            resultado.append("Faltou adicionar fecha-te-sesamo para fechar bloco de comando\n");

            if (e.currentToken != null) {
                resultado.append("[POSICAO]").append(e.currentToken.beginLine)
                         .append(",").append(e.currentToken.beginColumn).append("[/POSICAO]");
            }
            return resultado.toString();
        }
    }

    return "ERRO DE SINTAXE: Erro nao recuperado - consulte relatorio de erros";
  }

  public static String handleTokenMgrError(TokenMgrError e) {
    String msg = e.getMessage();
    StringBuilder resultado = new StringBuilder();

    int linha = 1;
    int coluna = 1;
    String charEncontrado = "?";

    try {
        String[] partes = msg.split(" ");
        for (int i = 0; i < partes.length; i++) {
            if (partes[i].equals("line") && i + 1 < partes.length) {
                linha = Integer.parseInt(partes[i + 1].replace(",", ""));
            }
            if (partes[i].equals("column") && i + 1 < partes.length) {
                coluna = Integer.parseInt(partes[i + 1].replace(".", ""));
            }
        }

        if (msg.contains("after prefix")) {
            int start = msg.indexOf("after prefix \"") + 14;
            int end = msg.indexOf("\"", start);
            if (start > 13 && end > start) {
                String prefixo = msg.substring(start, end);
                charEncontrado = prefixo;
                coluna = Math.max(1, coluna - prefixo.length());
            }
        } else if (msg.contains("Encountered:") && msg.contains("(")) {
            int parenteseAbre = msg.lastIndexOf("(");
            int parenteseFecha = msg.indexOf(")", parenteseAbre);

            if (parenteseAbre != -1 && parenteseFecha != -1) {
                String codigoStr = msg.substring(parenteseAbre + 1, parenteseFecha).trim();

                if (codigoStr.matches("\\d+")) {
                    try {
                        int codigoAscii = Integer.parseInt(codigoStr);
                        charEncontrado = Character.toString((char) codigoAscii);
                    } catch (NumberFormatException ex) {
                        charEncontrado = codigoStr;
                    }
                } else {
                    charEncontrado = codigoStr;
                }
            }
        } else {
            int aspasAbre = msg.indexOf("'");
            int aspasFecha = msg.indexOf("'", aspasAbre + 1);
            if (aspasAbre != -1 && aspasFecha != -1) {
                charEncontrado = msg.substring(aspasAbre + 1, aspasFecha);
            }
        }
    } catch (Exception ex) {
    }

    if (charEncontrado.startsWith("'") && charEncontrado.endsWith("'") && charEncontrado.length() > 1) {
        charEncontrado = charEncontrado.substring(1, charEncontrado.length() - 1);
    }

    resultado.append("ERRO LEXICO\n");
    resultado.append("Caractere invalido '").append(charEncontrado).append("' encontrado");

    String sugestao = gerarSugestaoErroLexico(charEncontrado);
    resultado.append("\n").append(sugestao);

    resultado.append("\n[POSICAO]").append(linha).append(",").append(coluna).append("[/POSICAO]");

    return resultado.toString();
  }

  private static String gerarSugestaoErroLexico(String charEncontrado) {
    if (charEncontrado.equals("=")) {
        return "Sugestao: Use 'receba' para atribuicao em vez de '='";
    } else if (charEncontrado.equals("@")) {
        return "Sugestao: Caractere '@' nao e permitido";
    } else if (charEncontrado.equals("?")) {
        return "Sugestao: Ponto de interrogacao nao e um operador valido";
    } else if (charEncontrado.equals(":")) {
        return "Sugestao: Dois pontos nao sao usados na linguagem";
    } else if (charEncontrado.equals("'")) {
        return "Sugestao: Utilize aspas duplas para strings";
    } else if (charEncontrado.equals("!")) {
        return "Sugestao: Use '!=' para diferenca";
    } else {
        return "Sugestao: Use apenas letras, numeros e os operadores definidos";
    }
  }

  public static void main(String args[]) {
    if (!parserInitialized) {
        new BrCompiler(System.in);
        parserInitialized = true;
    }

    BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));

    while (true) {
        System.out.println("na minha maquina funciona!");
        System.out.print("comece a digitar sua gambiarra:");

        try {
            String line = reader.readLine();

            if (line == null) {
                System.out.println("\nSaindo...");
                break;
            }

            line = line.trim();

            if (line.isEmpty()) {
                continue;
            }

            ErrorManager.clear();
            eof = false;
            lastError = null;
            delimiterBalancer = new DelimiterBalancer();
            balanceException = null;

            BrCompiler.ReInit(new StringReader(line));

            boolean hasBalanceError = false;
            String balanceErrorMsg = null;

            try {
                BrCompiler.main();
            } catch (ParseEOFException e) {
                System.out.println("ERRO FATAL: " + e.getMessage());
                ErrorManager.addError(new ParseException("EOF inesperado"), "main", null);
            } catch (ParseException e) {
                ErrorManager.addError(e, "main", null);
            } finally {
                // Verifica erros de balanceamento durante tokenização
                if (balanceException != null) {
                    hasBalanceError = true;
                    balanceErrorMsg = balanceException.getMessage();
                } else {
                    // Verifica o balanceamento no final, se não houve erro durante tokenização
                    try {
                        delimiterBalancer.checkBalance();
                    } catch (DelimiterBalancer.UnbalancedDelimiterException ex) {
                        hasBalanceError = true;
                        balanceErrorMsg = ex.getMessage();
                    }
                }
            }

            // Exibe erros de balanceamento
            if (hasBalanceError) {
                System.out.println("ERRO DE BALANCEAMENTO: " + balanceErrorMsg);
            }

            // Exibe resultado final
            if (ErrorManager.hasErrors() || hasBalanceError) {
                System.out.println("\nNOK.");
                if (ErrorManager.hasErrors()) {
                    System.out.println(ErrorManager.getErrorReport());
                }
            } else {
                System.out.println("\nOK.");
            }

        } catch (TokenMgrError e) {
            System.out.println("NOK.");
            System.out.println(handleTokenMgrError(e));

        } catch (Exception e) {
            System.out.println("NOK.");
            System.out.println("ERRO INESPERADO: " + e.getMessage());

            if (e.toString().contains("Stream closed") || e.toString().contains("null")) {
                System.out.println("Saindo...");
                break;
            }
        }
    }
  }

  static public String im(int x) {
    int k;
    String s;
    s = tokenImage[x];
    k = s.lastIndexOf("\"");
    try {
      s = s.substring(1,k);
    }
    catch (StringIndexOutOfBoundsException e) {}
    return s;
  }

  static Token lastError = null;
  static boolean eof;

  static void consumeUntil(RecoverySet g, ParseException e, String met) throws ParseEOFException {
    Token tok;

    ErrorManager.addError(e, met, g);
    ErrorManager.startRecovery();
    printDetalhesErro(e);

    System.out.println("\n*** " + met + " ***");
    System.out.println("    Conjunto de sincronizacao: " + g);

    if (g == null) {
        ErrorManager.endRecovery();
        throw new ParseEOFException("Conjunto de sincronizacao nulo em " + met);
    }

    tok = getToken(1);

    while (true) {
        if (g.contains(tok.kind)) {
            System.out.println("    Token sincronizado: '" + im(tok.kind) + "'");
            ErrorManager.endRecovery();
            return;
        }

        if (tok.kind == EOF) {
            eof = true;
            break;
        }

        System.out.println("    Ignorando o token: '" + im(tok.kind) + "'");
        ErrorManager.tokenConsumed();

        // Processa delimitadores mesmo durante recuperação para manter balanceamento
        if (tok.kind == ABREBLOCO || tok.kind == FECHABLOCO ||
            tok.kind == ABRIREXP || tok.kind == FECHAREXP) {
            try {
                delimiterBalancer.processToken(tok.kind, tok.beginLine, tok.beginColumn);
            } catch (DelimiterBalancer.UnbalancedDelimiterException ex) {
                // Durante recuperação, ignora erros de balanceamento temporários
                // O balanceamento final será verificado no método main
            }
        }

        getNextToken();
        tok = getToken(1);
    }

    ErrorManager.endRecovery();

    if (eof && g.contains(EOF)) {
        System.out.println("    EOF sincronizado - fim do arquivo");
        return;
    }

    if (eof) {
        throw new ParseEOFException("EOF alcancado durante recuperacao em " + met + " - esperava: " + g);
    }

    throw new ParseEOFException("Sem sincronizacao em " + met);
  }

  static void printDetalhesErro(ParseException e) {
    StringBuilder sb = new StringBuilder();
    Token tokenErro = null;

    if (e.currentToken != null && e.currentToken.next != null) {
        tokenErro = e.currentToken.next;
    } else if (e.currentToken != null) {
        tokenErro = e.currentToken;
    }

    String tokenEncontrado = (tokenErro != null && tokenErro.image != null) ? tokenErro.image : "EOF";

    sb.append("Token encontrado: '").append(tokenEncontrado).append("'\n");

    if (e.expectedTokenSequences != null && e.expectedTokenSequences.length > 0) {
        sb.append("Era esperado: ");
        boolean firstSeq = true;
        for (int[] seq : e.expectedTokenSequences) {
            if (!firstSeq) sb.append(" ou ");
            for (int i = 0; i < seq.length; i++) {
                if (i > 0) sb.append(" ");
                sb.append("'").append(obterTokenPortugues(seq[i])).append("'");
            }
            firstSeq = false;
        }
        sb.append("\n");
    }

    System.out.print(sb.toString());
  }

  static final public void main() throws ParseException {/*@bgen(jjtree) main */
  SimpleNode jjtn000 = new SimpleNode(JJTMAIN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.main;
    try {
      try {
        jj_consume_token(INICIOPROG);
        jj_consume_token(ABREBLOCO);
        bloco();
        jj_consume_token(FECHABLOCO);
      } catch (ParseException e) {
consumeUntil(g, e, "main");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void bloco() throws ParseException {/*@bgen(jjtree) bloco */
  SimpleNode jjtn000 = new SimpleNode(JJTBLOCO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.bloco;
    try {
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case PRINT:
        case SCAN:
        case FOR:
        case WHILE:
        case FUNCAO:
        case RETURN:
        case LISTA:
        case PILHA:
        case INT:
        case FLOAT:
        case STRING:
        case BOOL:
        case CONDICIONAL:
        case IDENTIFICADOR:{
          ;
          break;
          }
        default:
          jj_la1[0] = jj_gen;
          break label_1;
        }
        try {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case PRINT:
          case SCAN:
          case FOR:
          case WHILE:
          case RETURN:
          case LISTA:
          case PILHA:
          case INT:
          case FLOAT:
          case STRING:
          case BOOL:
          case CONDICIONAL:
          case IDENTIFICADOR:{
            comando();
            break;
            }
          case FUNCAO:{
            declaraFuncao();
            break;
            }
          default:
            jj_la1[1] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        } catch (ParseException e) {
consumeUntil(g, e, "bloco");
        }
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  static final public void comando() throws ParseException {/*@bgen(jjtree) comando */
  SimpleNode jjtn000 = new SimpleNode(JJTCOMANDO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.comando;
    try {
      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LISTA:
        case PILHA:
        case INT:
        case FLOAT:
        case STRING:
        case BOOL:{
          declaraVariavel();
          break;
          }
        case CONDICIONAL:{
          expressaoCondicional();
          break;
          }
        case IDENTIFICADOR:{
          comandoIdentificador();
          break;
          }
        case PRINT:{
          print();
          break;
          }
        case SCAN:{
          scan();
          break;
          }
        case WHILE:{
          whileLoop();
          break;
          }
        case FOR:{
          forLoop();
          break;
          }
        case RETURN:{
          retorno();
          break;
          }
        default:
          jj_la1[2] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      } catch (ParseException e) {
consumeUntil(g, e, "comando");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
       jjtree.clearNodeScope(jjtn000);
       jjtc000 = false;
     } else {
       jjtree.popNode();
     }
     if (jjte000 instanceof RuntimeException) {
       {if (true) throw (RuntimeException)jjte000;}
     }
     if (jjte000 instanceof ParseException) {
       {if (true) throw (ParseException)jjte000;}
     }
     {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
       jjtree.closeNodeScope(jjtn000, true);
     }
    }
}

  static final public void comandoIdentificador() throws ParseException {/*@bgen(jjtree) comandoIdentificador */
  SimpleNode jjtn000 = new SimpleNode(JJTCOMANDOIDENTIFICADOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.comandoIdentificador;
    try {
      try {
        jj_consume_token(IDENTIFICADOR);
        comandoIdentificadorSufixo();
      } catch (ParseException e) {
consumeUntil(g, e, "comandoIdentificador");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void comandoIdentificadorSufixo() throws ParseException {/*@bgen(jjtree) comandoIdentificadorSufixo */
  SimpleNode jjtn000 = new SimpleNode(JJTCOMANDOIDENTIFICADORSUFIXO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.comandoIdentificadorSufixo;
    try {
      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ATRIBUICAO:{
          jj_consume_token(ATRIBUICAO);
          Expressao();
          jj_consume_token(FIMESTRUTURA);
          break;
          }
        case ABRIRFUNC:{
          jj_consume_token(ABRIRFUNC);
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case TAMANHO:
          case TOPO:
          case PILHA_VAZIA:
          case TRUE:
          case FALSE:
          case ABRIREXP:
          case ABRIRFUNC:
          case LITERAL_STRING:
          case CONSTANTE_INT:
          case CONSTANTE_FLOAT:
          case IDENTIFICADOR:{
            ListaExpressoes();
            break;
            }
          default:
            jj_la1[3] = jj_gen;
            ;
          }
          jj_consume_token(FECHARFUNC);
          jj_consume_token(FIMESTRUTURA);
          break;
          }
        case ADICIONAR:{
          jj_consume_token(ADICIONAR);
          Expressao();
          jj_consume_token(FIMESTRUTURA);
          break;
          }
        case REMOVER:{
          jj_consume_token(REMOVER);
          jj_consume_token(ABRIREXP);
          Expressao();
          jj_consume_token(FECHAREXP);
          jj_consume_token(FIMESTRUTURA);
          break;
          }
        case EMPILHAR:{
          jj_consume_token(EMPILHAR);
          Expressao();
          jj_consume_token(FIMESTRUTURA);
          break;
          }
        case DESEMPILHAR:{
          jj_consume_token(DESEMPILHAR);
          jj_consume_token(FIMESTRUTURA);
          break;
          }
        case FIMESTRUTURA:
        case ABRIREXP:
        case SOMA:
        case SUBTRACAO:{
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case ABRIREXP:{
            jj_consume_token(ABRIREXP);
            switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
            case TAMANHO:
            case TOPO:
            case PILHA_VAZIA:
            case TRUE:
            case FALSE:
            case ABRIREXP:
            case ABRIRFUNC:
            case LITERAL_STRING:
            case CONSTANTE_INT:
            case CONSTANTE_FLOAT:
            case IDENTIFICADOR:{
              ListaExpressoes();
              break;
              }
            default:
              jj_la1[4] = jj_gen;
              ;
            }
            jj_consume_token(FECHAREXP);
            break;
            }
          default:
            jj_la1[5] = jj_gen;
            ;
          }
          sufixoExpressao();
          break;
          }
        default:
          jj_la1[6] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      } catch (ParseException e) {
consumeUntil(g, e, "comandoIdentificadorSufixo");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void sufixoExpressao() throws ParseException {/*@bgen(jjtree) sufixoExpressao */
  SimpleNode jjtn000 = new SimpleNode(JJTSUFIXOEXPRESSAO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.sufixoExpressao;
    try {
      try {
        label_2:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case SOMA:
          case SUBTRACAO:{
            ;
            break;
            }
          default:
            jj_la1[7] = jj_gen;
            break label_2;
          }
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case SOMA:{
            jj_consume_token(SOMA);
            break;
            }
          case SUBTRACAO:{
            jj_consume_token(SUBTRACAO);
            break;
            }
          default:
            jj_la1[8] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          fator();
        }
        jj_consume_token(FIMESTRUTURA);
      } catch (ParseException e) {
consumeUntil(g, e, "sufixoExpressao");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void declaraVariavel() throws ParseException {/*@bgen(jjtree) declaraVariavel */
  SimpleNode jjtn000 = new SimpleNode(JJTDECLARAVARIAVEL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.declaraVariavel;
    try {
      try {
        tipoDado();
        ListaIdentificadores();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ATRIBUICAO:{
          jj_consume_token(ATRIBUICAO);
          ListaExpressoes();
          break;
          }
        default:
          jj_la1[9] = jj_gen;
          ;
        }
        jj_consume_token(FIMESTRUTURA);
      } catch (ParseException e) {
consumeUntil(g, e, "declaraVariavel");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  static final public void tipoDado() throws ParseException {/*@bgen(jjtree) tipoDado */
  SimpleNode jjtn000 = new SimpleNode(JJTTIPODADO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.tipoDado;
    try {
      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case INT:{
          jj_consume_token(INT);
          break;
          }
        case FLOAT:{
          jj_consume_token(FLOAT);
          break;
          }
        case STRING:{
          jj_consume_token(STRING);
          break;
          }
        case BOOL:{
          jj_consume_token(BOOL);
          break;
          }
        case LISTA:{
          tipoLista();
          break;
          }
        case PILHA:{
          tipoPilha();
          break;
          }
        default:
          jj_la1[10] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      } catch (ParseException e) {
consumeUntil(g, e, "tipoDado");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  static final public void ListaIdentificadores() throws ParseException {/*@bgen(jjtree) ListaIdentificadores */
  SimpleNode jjtn000 = new SimpleNode(JJTLISTAIDENTIFICADORES);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.listaIdentificadores;
    try {
      try {
        jj_consume_token(IDENTIFICADOR);
        label_3:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case VIRGULA:{
            ;
            break;
            }
          default:
            jj_la1[11] = jj_gen;
            break label_3;
          }
          jj_consume_token(VIRGULA);
          jj_consume_token(IDENTIFICADOR);
        }
      } catch (ParseException e) {
consumeUntil(g, e, "ListaIdentificadores");
      }
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  static final public void ListaExpressoes() throws ParseException {/*@bgen(jjtree) ListaExpressoes */
  SimpleNode jjtn000 = new SimpleNode(JJTLISTAEXPRESSOES);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.listaExpressoes;
    try {
      try {
        Expressao();
        label_4:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case VIRGULA:{
            ;
            break;
            }
          default:
            jj_la1[12] = jj_gen;
            break label_4;
          }
          jj_consume_token(VIRGULA);
          Expressao();
        }
      } catch (ParseException e) {
consumeUntil(g, e, "ListaExpressoes");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  static final public void Expressao() throws ParseException {/*@bgen(jjtree) Expressao */
  SimpleNode jjtn000 = new SimpleNode(JJTEXPRESSAO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.expressao;
    try {
      try {
        fator();
        label_5:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case SOMA:
          case SUBTRACAO:{
            ;
            break;
            }
          default:
            jj_la1[13] = jj_gen;
            break label_5;
          }
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case SOMA:{
            jj_consume_token(SOMA);
            break;
            }
          case SUBTRACAO:{
            jj_consume_token(SUBTRACAO);
            break;
            }
          default:
            jj_la1[14] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          fator();
        }
      } catch (ParseException e) {
consumeUntil(g, e, "Expressao");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  static final public void fator() throws ParseException {/*@bgen(jjtree) fator */
  SimpleNode jjtn000 = new SimpleNode(JJTFATOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.fator;
    try {
      try {
        termo();
        label_6:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case MULTIPLICACAO:
          case DIVISAO:{
            ;
            break;
            }
          default:
            jj_la1[15] = jj_gen;
            break label_6;
          }
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case MULTIPLICACAO:{
            jj_consume_token(MULTIPLICACAO);
            break;
            }
          case DIVISAO:{
            jj_consume_token(DIVISAO);
            break;
            }
          default:
            jj_la1[16] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          termo();
        }
      } catch (ParseException e) {
consumeUntil(g, e, "fator");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
       jjtree.clearNodeScope(jjtn000);
       jjtc000 = false;
     } else {
       jjtree.popNode();
     }
     if (jjte000 instanceof RuntimeException) {
       {if (true) throw (RuntimeException)jjte000;}
     }
     if (jjte000 instanceof ParseException) {
       {if (true) throw (ParseException)jjte000;}
     }
     {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
       jjtree.closeNodeScope(jjtn000, true);
     }
    }
}

  static final public void termo() throws ParseException {/*@bgen(jjtree) termo */
  SimpleNode jjtn000 = new SimpleNode(JJTTERMO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.termo;
    try {
      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IDENTIFICADOR:{
          jj_consume_token(IDENTIFICADOR);
          termoIdentificadorSufixo();
          break;
          }
        case CONSTANTE_INT:{
          jj_consume_token(CONSTANTE_INT);
          break;
          }
        case CONSTANTE_FLOAT:{
          jj_consume_token(CONSTANTE_FLOAT);
          break;
          }
        case LITERAL_STRING:{
          jj_consume_token(LITERAL_STRING);
          break;
          }
        case TRUE:{
          jj_consume_token(TRUE);
          break;
          }
        case FALSE:{
          jj_consume_token(FALSE);
          break;
          }
        case TAMANHO:{
          jj_consume_token(TAMANHO);
          jj_consume_token(IDENTIFICADOR);
          break;
          }
        case ABRIREXP:{
          inicializacaoLista();
          break;
          }
        case TOPO:{
          jj_consume_token(TOPO);
          jj_consume_token(IDENTIFICADOR);
          break;
          }
        case PILHA_VAZIA:{
          jj_consume_token(PILHA_VAZIA);
          jj_consume_token(IDENTIFICADOR);
          break;
          }
        case ABRIRFUNC:{
          jj_consume_token(ABRIRFUNC);
          Expressao();
          jj_consume_token(FECHARFUNC);
          break;
          }
        default:
          jj_la1[17] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      } catch (ParseException e) {
consumeUntil(g, e, "termo");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void termoIdentificadorSufixo() throws ParseException {/*@bgen(jjtree) termoIdentificadorSufixo */
  SimpleNode jjtn000 = new SimpleNode(JJTTERMOIDENTIFICADORSUFIXO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.termoIdentificadorSufixo;
    try {
      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ABRIRFUNC:{
          jj_consume_token(ABRIRFUNC);
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case TAMANHO:
          case TOPO:
          case PILHA_VAZIA:
          case TRUE:
          case FALSE:
          case ABRIREXP:
          case ABRIRFUNC:
          case LITERAL_STRING:
          case CONSTANTE_INT:
          case CONSTANTE_FLOAT:
          case IDENTIFICADOR:{
            ListaExpressoes();
            break;
            }
          default:
            jj_la1[18] = jj_gen;
            ;
          }
          jj_consume_token(FECHARFUNC);
          break;
          }
        default:
          jj_la1[21] = jj_gen;
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case ABRIREXP:{
            jj_consume_token(ABRIREXP);
            switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
            case TAMANHO:
            case TOPO:
            case PILHA_VAZIA:
            case TRUE:
            case FALSE:
            case ABRIREXP:
            case ABRIRFUNC:
            case LITERAL_STRING:
            case CONSTANTE_INT:
            case CONSTANTE_FLOAT:
            case IDENTIFICADOR:{
              ListaExpressoes();
              break;
              }
            default:
              jj_la1[19] = jj_gen;
              ;
            }
            jj_consume_token(FECHAREXP);
            break;
            }
          default:
            jj_la1[20] = jj_gen;
            ;
          }
        }
      } catch (ParseException e) {
consumeUntil(g, e, "termoIdentificadorSufixo");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void operadorLogico() throws ParseException {/*@bgen(jjtree) operadorLogico */
  SimpleNode jjtn000 = new SimpleNode(JJTOPERADORLOGICO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.expressao;
    try {
      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case OPDIF:{
          jj_consume_token(OPDIF);
          break;
          }
        case OPIGUAL:{
          jj_consume_token(OPIGUAL);
          break;
          }
        case OPMAIOR:{
          jj_consume_token(OPMAIOR);
          break;
          }
        case OPMENOR:{
          jj_consume_token(OPMENOR);
          break;
          }
        case OPMAIORIGUAL:{
          jj_consume_token(OPMAIORIGUAL);
          break;
          }
        case OPMENORIGUAL:{
          jj_consume_token(OPMENORIGUAL);
          break;
          }
        case OPAND:{
          jj_consume_token(OPAND);
          break;
          }
        case OPOR:{
          jj_consume_token(OPOR);
          break;
          }
        default:
          jj_la1[22] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      } catch (ParseException e) {
consumeUntil(g, e, "operadorLogico");
      }
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void expressaoLogica() throws ParseException {/*@bgen(jjtree) expressaoLogica */
  SimpleNode jjtn000 = new SimpleNode(JJTEXPRESSAOLOGICA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.expressao;
    try {
      try {
        Expressao();
        operadorLogico();
        Expressao();
      } catch (ParseException e) {
consumeUntil(g, e, "expressaoLogica");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void expressaoCondicional() throws ParseException {/*@bgen(jjtree) expressaoCondicional */
  SimpleNode jjtn000 = new SimpleNode(JJTEXPRESSAOCONDICIONAL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.expressaoCondicional;
    try {
      try {
        condicao();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case SENAO:{
          jj_consume_token(SENAO);
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case CONDICIONAL:{
            condicao();
            break;
            }
          case ABREBLOCO:{
            jj_consume_token(ABREBLOCO);
            bloco();
            jj_consume_token(FECHABLOCO);
            break;
            }
          default:
            jj_la1[23] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          break;
          }
        default:
          jj_la1[24] = jj_gen;
          ;
        }
      } catch (ParseException e) {
consumeUntil(g, e, "expressaoCondicional");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void condicao() throws ParseException {/*@bgen(jjtree) condicao */
  SimpleNode jjtn000 = new SimpleNode(JJTCONDICAO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.condicao;
    try {
      try {
        jj_consume_token(CONDICIONAL);
        jj_consume_token(ABRIREXP);
        expressaoLogica();
        jj_consume_token(FECHAREXP);
        jj_consume_token(ABREBLOCO);
        bloco();
        jj_consume_token(FECHABLOCO);
      } catch (ParseException e) {
consumeUntil(g, e, "condicao");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void print() throws ParseException {/*@bgen(jjtree) print */
  SimpleNode jjtn000 = new SimpleNode(JJTPRINT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.print;
    try {
      try {
        jj_consume_token(PRINT);
        ListaExpressoes();
        jj_consume_token(FIMESTRUTURA);
      } catch (ParseException e) {
consumeUntil(g, e, "print");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  static final public void scan() throws ParseException {/*@bgen(jjtree) scan */
  SimpleNode jjtn000 = new SimpleNode(JJTSCAN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.scan;
    try {
      try {
        jj_consume_token(SCAN);
        jj_consume_token(IDENTIFICADOR);
        jj_consume_token(FIMESTRUTURA);
      } catch (ParseException e) {
consumeUntil(g, e, "scan");
      }
    } finally {
if (jjtc000) {
       jjtree.closeNodeScope(jjtn000, true);
     }
    }
}

  static final public void whileLoop() throws ParseException {/*@bgen(jjtree) whileLoop */
  SimpleNode jjtn000 = new SimpleNode(JJTWHILELOOP);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.whileLoop;
    try {
      try {
        jj_consume_token(WHILE);
        jj_consume_token(ABRIREXP);
        expressaoLogica();
        jj_consume_token(FECHAREXP);
        jj_consume_token(ABREBLOCO);
        bloco();
        jj_consume_token(FECHABLOCO);
      } catch (ParseException e) {
consumeUntil(g, e, "whileLoop");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  static final public void forLoop() throws ParseException {/*@bgen(jjtree) forLoop */
  SimpleNode jjtn000 = new SimpleNode(JJTFORLOOP);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.forLoop;
    try {
      try {
        jj_consume_token(FOR);
        jj_consume_token(ABRIREXP);
        atribuicaoFor();
        jj_consume_token(SEPARADOR);
        expressaoLogica();
        jj_consume_token(SEPARADOR);
        atribuicaoFor();
        jj_consume_token(FECHAREXP);
        jj_consume_token(ABREBLOCO);
        bloco();
        jj_consume_token(FECHABLOCO);
      } catch (ParseException e) {
consumeUntil(g, e, "forLoop");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void atribuicaoFor() throws ParseException {/*@bgen(jjtree) atribuicaoFor */
  SimpleNode jjtn000 = new SimpleNode(JJTATRIBUICAOFOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.atribuicaoFor;
    try {
      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LISTA:
        case PILHA:
        case INT:
        case FLOAT:
        case STRING:
        case BOOL:{
          tipoDado();
          break;
          }
        default:
          jj_la1[25] = jj_gen;
          ;
        }
        jj_consume_token(IDENTIFICADOR);
        jj_consume_token(ATRIBUICAO);
        Expressao();
      } catch (ParseException e) {
consumeUntil(g, e, "atribuicaoFor");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void declaraFuncao() throws ParseException {/*@bgen(jjtree) declaraFuncao */
  SimpleNode jjtn000 = new SimpleNode(JJTDECLARAFUNCAO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.declaraFuncao;
    try {
      try {
        jj_consume_token(FUNCAO);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LISTA:
        case PILHA:
        case INT:
        case FLOAT:
        case STRING:
        case BOOL:{
          tipoDado();
          break;
          }
        default:
          jj_la1[26] = jj_gen;
          ;
        }
        jj_consume_token(IDENTIFICADOR);
        jj_consume_token(ABRIRFUNC);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LISTA:
        case PILHA:
        case INT:
        case FLOAT:
        case STRING:
        case BOOL:{
          listaParametros();
          break;
          }
        default:
          jj_la1[27] = jj_gen;
          ;
        }
        jj_consume_token(FECHARFUNC);
        jj_consume_token(ABREBLOCO);
        bloco();
        jj_consume_token(FECHABLOCO);
      } catch (ParseException e) {
consumeUntil(g, e, "declaraFuncao");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
     jjtree.clearNodeScope(jjtn000);
     jjtc000 = false;
   } else {
     jjtree.popNode();
   }
   if (jjte000 instanceof RuntimeException) {
     {if (true) throw (RuntimeException)jjte000;}
   }
   if (jjte000 instanceof ParseException) {
     {if (true) throw (ParseException)jjte000;}
   }
   {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
     jjtree.closeNodeScope(jjtn000, true);
   }
    }
}

  static final public void listaParametros() throws ParseException {/*@bgen(jjtree) listaParametros */
  SimpleNode jjtn000 = new SimpleNode(JJTLISTAPARAMETROS);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.listaParametros;
    try {
      try {
        parametro();
        label_7:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case VIRGULA:{
            ;
            break;
            }
          default:
            jj_la1[28] = jj_gen;
            break label_7;
          }
          jj_consume_token(VIRGULA);
          parametro();
        }
      } catch (ParseException e) {
consumeUntil(g, e, "listaParametros");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void parametro() throws ParseException {/*@bgen(jjtree) parametro */
  SimpleNode jjtn000 = new SimpleNode(JJTPARAMETRO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.parametro;
    try {
      try {
        tipoDado();
        jj_consume_token(IDENTIFICADOR);
      } catch (ParseException e) {
consumeUntil(g, e, "parametro");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void retorno() throws ParseException {/*@bgen(jjtree) retorno */
  SimpleNode jjtn000 = new SimpleNode(JJTRETORNO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.retorno;
    try {
      try {
        jj_consume_token(RETURN);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case TAMANHO:
        case TOPO:
        case PILHA_VAZIA:
        case TRUE:
        case FALSE:
        case ABRIREXP:
        case ABRIRFUNC:
        case LITERAL_STRING:
        case CONSTANTE_INT:
        case CONSTANTE_FLOAT:
        case IDENTIFICADOR:{
          Expressao();
          break;
          }
        default:
          jj_la1[29] = jj_gen;
          ;
        }
        jj_consume_token(FIMESTRUTURA);
      } catch (ParseException e) {
consumeUntil(g, e, "retorno");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  static final public void tipoLista() throws ParseException {/*@bgen(jjtree) tipoLista */
  SimpleNode jjtn000 = new SimpleNode(JJTTIPOLISTA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.tipoLista;
    try {
      try {
        jj_consume_token(LISTA);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case INT:{
          jj_consume_token(INT);
          break;
          }
        case FLOAT:{
          jj_consume_token(FLOAT);
          break;
          }
        case STRING:{
          jj_consume_token(STRING);
          break;
          }
        case BOOL:{
          jj_consume_token(BOOL);
          break;
          }
        default:
          jj_la1[30] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      } catch (ParseException e) {
consumeUntil(g, e, "tipoLista");
      }
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void inicializacaoLista() throws ParseException {/*@bgen(jjtree) inicializacaoLista */
  SimpleNode jjtn000 = new SimpleNode(JJTINICIALIZACAOLISTA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.inicializacaoLista;
    try {
      try {
        jj_consume_token(ABRIREXP);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case TAMANHO:
        case TOPO:
        case PILHA_VAZIA:
        case TRUE:
        case FALSE:
        case ABRIREXP:
        case ABRIRFUNC:
        case LITERAL_STRING:
        case CONSTANTE_INT:
        case CONSTANTE_FLOAT:
        case IDENTIFICADOR:{
          ListaExpressoes();
          break;
          }
        default:
          jj_la1[31] = jj_gen;
          ;
        }
        jj_consume_token(FECHAREXP);
      } catch (ParseException e) {
consumeUntil(g, e, "inicializacaoLista");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void tipoPilha() throws ParseException {/*@bgen(jjtree) tipoPilha */
  SimpleNode jjtn000 = new SimpleNode(JJTTIPOPILHA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet g = Follow.tipoPilha;
    try {
      try {
        jj_consume_token(PILHA);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case INT:{
          jj_consume_token(INT);
          break;
          }
        case FLOAT:{
          jj_consume_token(FLOAT);
          break;
          }
        case STRING:{
          jj_consume_token(STRING);
          break;
          }
        case BOOL:{
          jj_consume_token(BOOL);
          break;
          }
        default:
          jj_la1[32] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      } catch (ParseException e) {
consumeUntil(g, e, "tipoPilha");
      }
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public BrCompilerTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[33];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x1e022de0,0x1e022de0,0x1e0229e0,0x60310000,0x60310000,0x0,0x800cc000,0x0,0x0,0x80000000,0x1e022000,0x1000,0x1000,0x0,0x0,0x0,0x0,0x60310000,0x60310000,0x60310000,0x0,0x0,0x0,0x800000,0x0,0x1e022000,0x1e022000,0x1e022000,0x1000,0x60310000,0x1e000000,0x60310000,0x1e000000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x402,0x402,0x402,0x7a8,0x7a8,0x8,0x3029,0x3000,0x3000,0x0,0x0,0x0,0x0,0x3000,0x3000,0xc000,0xc000,0x7a8,0x7a8,0x7a8,0x8,0x20,0xff0000,0x2,0x4,0x0,0x0,0x0,0x0,0x7a8,0x0,0x7a8,0x0,};
	}

  /** Constructor with InputStream. */
  public BrCompiler(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public BrCompiler(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new BrCompilerTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 33; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 33; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public BrCompiler(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new BrCompilerTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 33; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new BrCompilerTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 33; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public BrCompiler(BrCompilerTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 33; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(BrCompilerTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 33; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[56];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 33; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 56; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
