/* BrCompiler.java */
/* Generated By:JavaCC: Do not edit this line. BrCompiler.java */
package compiler;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.StringReader;

public class BrCompiler implements BrCompilerConstants {

  private static boolean parserInitialized = false;

  // mapeamento de tokens 
  private static String obterTokenPortugues(int tipoToken) {
    switch(tipoToken) {
      case INICIOPROG: return "gambiarra";
      case ABREBLOCO: return "abre-te-sesamo";
      case FECHABLOCO: return "fecha-te-sesamo";
      case INT: return "stonks";
      case FLOAT: return "fiado";
      case STRING: return "textao";
      case BOOL: return "eh-migue";
      case TRUE: return "sim";
      case FALSE: return "nao";
      case ATRIBUICAO: return "receba";
      case FIMESTRUTURA: return "br";
      case CONDICIONAL: return "sepa";
      case SENAO: return "da-teus-pulo";
      case ABRIREXP: return "[";
      case FECHAREXP: return "]";
      case ABRIRFUNC: return "(";
      case FECHARFUNC: return ")";
      case PRINT: return "printa";
      case SCAN: return "papa-entrada";
      case FOR: return "pet";
      case WHILE: return "repet";
      case FUNCAO: return "vai-filhao";
      case RETURN: return "devolva";
      case SEPARADOR: return ";";
      case SOMA: return "+";
      case SUBTRACAO: return "-";
      case MULTIPLICACAO: return "*";
      case DIVISAO: return "/";
      case OPMAIOR: return ">";
      case OPIGUAL: return "==";
      case OPMENOR: return "<";
      case OPMAIORIGUAL: return ">=";
      case OPMENORIGUAL: return "<=";
      case OPDIF: return "!=";
      case OPAND: return "&&";
      case OPOR: return "|";
      case IDENTIFICADOR: return "identificador";
      case CONSTANTE_INT: return "numero inteiro";
      case CONSTANTE_FLOAT: return "numero decimal";
      case LITERAL_STRING: return "texto";
      case VIRGULA: return "virgula (,)";
      case LISTA: return "tropa-do-gordao";
      case ADICIONAR: return "recrutar";
      case REMOVER: return "expulsar";
      case TAMANHO: return "tamanho";
      case PILHA: return "sanduiche-iche";
      case EMPILHAR: return "montar-sanduba";
      case DESEMPILHAR: return "comer-sanduba";
      case TOPO: return "olho-gordo";
      case PILHA_VAZIA: return "farelo";
      default: return "token desconhecido";
    }
  }

//conta cada delimitador de bloco aberto
private static int verificarBlocos(String input) {
    int nivel = 0;
    String[] tokens = input.split("\\s+");

    for (String token : tokens) {
        if (token.equals("abre-te-sesamo")) {
            nivel++;
        } else if (token.equals("fecha-te-sesamo")) {
            nivel--;
            if (nivel < 0) {
                return -1; // erro: fechamento sem abertura
            }
        }
    }
    return nivel; // 0 = balanceado, >0 = blocos não fechados
}

// metodo pra tratar erros e gerar mensagens de erro em portugues
public static void handleParseError(ParseException e) {
    // Detecção melhorada para bloco não fechado
    boolean blocoNaoFechado = false;

    if (e.currentToken != null) {
        // Caso 1: Token atual é EOF - chegamos ao fim sem fechar o bloco
        if (e.currentToken.kind == EOF) {
            blocoNaoFechado = true;
        }
        // Caso 2: Próximo token é EOF - estamos no último token antes do fim
        else if (e.currentToken.next != null && e.currentToken.next.kind == EOF) {
            blocoNaoFechado = true;
        }
        // Caso 3: Verifica se estava esperando FECHABLOCO mas não encontrou
        else if (e.expectedTokenSequences != null) {
            for (int[] sequence : e.expectedTokenSequences) {
                for (int tokenType : sequence) {
                    if (tokenType == FECHABLOCO) {
                        blocoNaoFechado = true;
                        break;
                    }
                }
                if (blocoNaoFechado) break;
            }
        }
    }

    if (blocoNaoFechado) {
        System.out.println("NOK.");
        System.out.println("ERRO DE SINTAXE: Bloco n\u00e3o fechado");
        System.out.println("Faltou adicionar 'fecha-te-sesamo' para fechar bloco de comando");

        // Tenta dar uma posição mais específica
        if (e.currentToken != null) {
            System.out.println("Erro detectado pr\u00f3ximo \u00e0 linha " + e.currentToken.beginLine +
                             ", coluna " + e.currentToken.beginColumn);
        }
        return;
    }

    // Resto do método para outros tipos de erro
    System.out.println("NOK.");
    System.out.println("ERRO DE SINTAXE:");

    Token currentToken = e.currentToken;
    Token tokenEncontrado = null;

    // tenta obter as info do token encontrado
    if (currentToken != null && currentToken.next != null) {
        tokenEncontrado = currentToken.next;
    } else if (currentToken != null) {
        tokenEncontrado = currentToken;
    } else {
        try {
            tokenEncontrado = getToken(1);
        } catch (Exception ex) {
            tokenEncontrado = null;
        }
    }

    // aqui mostra informacoes do token que encontrou
    if (tokenEncontrado != null && tokenEncontrado.image != null) {
        System.out.println("Token encontrado: '" + tokenEncontrado.image + "' na linha " +
                         tokenEncontrado.beginLine + ", coluna " + tokenEncontrado.beginColumn);
    } else {
        if (currentToken != null) {
            String tokenImage = currentToken.image != null ? currentToken.image : "EOF";
            int linha = currentToken.beginLine > 0 ? currentToken.beginLine : 1;
            int coluna = currentToken.beginColumn > 0 ? currentToken.beginColumn : 1;
            System.out.println("Token encontrado: '" + tokenImage + "' na linha " + linha + ", coluna " + coluna);
        } else {
            System.out.println("Token encontrado: fim de arquivo inesperado");
        }
    }

    // aqui mostra os tokens esperados
    if (e.expectedTokenSequences.length > 0) {
        System.out.print("Era esperado: ");
        boolean first = true;
        for (int[] sequence : e.expectedTokenSequences) {
            if (!first) System.out.print(" ou ");
            for (int i = 0; i < sequence.length; i++) {
                if (i > 0) System.out.print(" ");
                System.out.print("'" + obterTokenPortugues(sequence[i]) + "'");
            }
            first = false;
        }
        System.out.println();
    }
}

//metodo pra tratar os erros léxicos em pt br

private static void handleTokenMgrError(TokenMgrError e) {
    String msg = e.getMessage();

    int linha = 1;
    int coluna = 1;
    String charEncontrado = "?";
    boolean problemaNoEspaco = false;

    try {
        // extrair linha e coluna
        String[] partes = msg.split(" ");
        for (int i = 0; i < partes.length; i++) {
            if (partes[i].equals("line") && i + 1 < partes.length) {
                linha = Integer.parseInt(partes[i + 1].replace(",", ""));
            }
            if (partes[i].equals("column") && i + 1 < partes.length) {
                coluna = Integer.parseInt(partes[i + 1].replace(".", ""));
            }
        }


        if (msg.contains("after prefix")) {

            int start = msg.indexOf("after prefix \"") + 14;
            int end = msg.indexOf("\"", start);
            if (start > 13 && end > start) {
                String prefixo = msg.substring(start, end);
                charEncontrado = prefixo;

                coluna = Math.max(1, coluna - prefixo.length());
            }
        } else if (msg.contains("Encountered:") && msg.contains("(")) {

            int parenteseAbre = msg.lastIndexOf("(");
            int parenteseFecha = msg.indexOf(")", parenteseAbre);

            if (parenteseAbre != -1 && parenteseFecha != -1) {
                String codigoStr = msg.substring(parenteseAbre + 1, parenteseFecha).trim();

                if (codigoStr.matches("\\d+")) {
                    try {
                        int codigoAscii = Integer.parseInt(codigoStr);
                        charEncontrado = Character.toString((char) codigoAscii);


                        if (codigoAscii == 32 && !msg.contains("after prefix")) {
                            problemaNoEspaco = true;
                        }
                    } catch (NumberFormatException ex) {
                        charEncontrado = codigoStr;
                    }
                } else {
                    charEncontrado = codigoStr;
                }
            }
        } else {

            int aspasAbre = msg.indexOf("'");
            int aspasFecha = msg.indexOf("'", aspasAbre + 1);
            if (aspasAbre != -1 && aspasFecha != -1) {
                charEncontrado = msg.substring(aspasAbre + 1, aspasFecha);
            }
        }



    } catch (Exception ex) {
        // manter valores padrao
    }

    if (charEncontrado.startsWith("'") && charEncontrado.endsWith("'") && charEncontrado.length() > 1) {
        charEncontrado = charEncontrado.substring(1, charEncontrado.length() - 1);
    }

    System.out.println("NOK.");
    System.out.println("ERRO L\u00c9XICO");
    System.out.println("Caractere inv\u00e1lido '" + charEncontrado + "' encontrado na linha " + linha + ", coluna " + coluna);

//sugestoes pre prontas
    if (charEncontrado.equals("=")) {
        System.out.println("Sugest\u00e3o: Use 'receba' para atribui\u00e7\u00e3o em vez de '='");
    } else if (charEncontrado.equals("@")) {
        System.out.println("Sugest\u00e3o: Caractere '@' n\u00e3o \u00e9 permitido. Use apenas caracteres v\u00e1lidos");
    }  else if (charEncontrado.equals("?")) {
        System.out.println("Sugest\u00e3o: Ponto de interroga\u00e7\u00e3o n\u00e3o \u00e9 um operador v\u00e1lido");
    } else if (charEncontrado.equals(":")) {
        System.out.println("Sugest\u00e3o: Dois pontos n\u00e3o s\u00e3o usados na linguagem");
    } else if (charEncontrado.equals("'")) {
        System.out.println("Sugest\u00e3o: Utilize aspas duplas para strings");
    } else if (charEncontrado.equals("!")) {
        System.out.println("Sugest\u00e3o: Use '!=' para diferen\u00e7a, ou verifique a sintaxe");
    } else {
        System.out.println("Sugest\u00e3o: Use apenas letras, n\u00fameros e os operadores definidos na linguagem");
    }

}

public static int one_line() throws ParseException {
    try {
        if (!parserInitialized) {
            new BrCompiler(System.in);
            parserInitialized = true;
        } else {
            BrCompiler.ReInit(System.in);
        }

        BrCompiler.main();
        return 0;
    } catch (ParseException e) {
        // verifica se o erro é devido a EOF (entrada incompleta)
        if (e.currentToken != null && e.currentToken.kind == EOF) {
            System.out.println("NOK.");
            System.out.println("ERRO DE SINTAXE: Entrada incompleta");
            System.out.println("Verifique se todos os blocos foram fechados com 'fecha-te-sesamo'");
            return -1; // codigo especial pra entrada incompleta
        }
        throw e;
    }
}


 public static void main(String args[]) throws ParseException {
    if (!parserInitialized) {
        new BrCompiler(System.in);
        parserInitialized = true;
    }

    BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));

    while (true) {
        System.out.println("na minha maquina funciona!");
        System.out.print("comece a digitar sua gambiarra:");

        try {
            String line = reader.readLine();

            // trata EOF (Ctrl+Z) corretamente
            if (line == null) {
                System.out.println("\nSaindo...");
                break;
            }

            line = line.trim();

            if (line.isEmpty()) {
                continue; // so continua se a linha estiver vazia
            }



            BrCompiler.ReInit(new StringReader(line));
            BrCompiler.main();
            System.out.println("OK.");

        } catch (ParseException e) {
            handleParseError(e);
        } catch (TokenMgrError e) {
            handleTokenMgrError(e);
        } catch (Exception e) {
            System.out.println("NOK.");
            System.out.println("ERRO INESPERADO: " + e.getMessage());

            // Se for erro de stream fechada (EOF), sai do programa
            if (e.toString().contains("Stream closed") || e.toString().contains("null")) {
                System.out.println("Saindo...");
                break;
            }
        }
    }
}

/* =====================================================
   REGRAS GRAMATICAIS REFATORADAS PARA LL(1)
   Eliminação de LOOKAHEADs através de Fatoração
   ===================================================== */
  static final public 
void main() throws ParseException {
    jj_consume_token(INICIOPROG);
    jj_consume_token(ABREBLOCO);
    bloco();
    jj_consume_token(FECHABLOCO);
}

  static final public void bloco() throws ParseException {
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PRINT:
      case SCAN:
      case FOR:
      case WHILE:
      case FUNCAO:
      case RETURN:
      case LISTA:
      case PILHA:
      case INT:
      case FLOAT:
      case STRING:
      case BOOL:
      case CONDICIONAL:
      case IDENTIFICADOR:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PRINT:
      case SCAN:
      case FOR:
      case WHILE:
      case RETURN:
      case LISTA:
      case PILHA:
      case INT:
      case FLOAT:
      case STRING:
      case BOOL:
      case CONDICIONAL:
      case IDENTIFICADOR:{
        comando();
        break;
        }
      case FUNCAO:{
        declaraFuncao();
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}

/* ========== COMANDO REFATORADO (SEM LOOKAHEADs) ========== */
  static final public void comando() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LISTA:
    case PILHA:
    case INT:
    case FLOAT:
    case STRING:
    case BOOL:{
      declaraVariavel();
      break;
      }
    case CONDICIONAL:{
      expressaoCondicional();
      break;
      }
    case IDENTIFICADOR:{
      comandoIdentificador();
      break;
      }
    case PRINT:{
      print();
      break;
      }
    case SCAN:{
      scan();
      break;
      }
    case WHILE:{
      whileLoop();
      break;
      }
    case FOR:{
      forLoop();
      break;
      }
    case RETURN:{
      retorno();
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

/* ===== NOVO: FATORAÇÃO PARA COMANDOS COM IDENTIFICADOR ===== */
/*
 * Esta produção resolve a ambiguidade eliminando os LOOKAHEADs
 * ao fatora todos os comandos que começam com IDENTIFICADOR
 */
  static final public void comandoIdentificador() throws ParseException {
    jj_consume_token(IDENTIFICADOR);
    comandoIdentificadorSufixo();
}

  static final public void comandoIdentificadorSufixo() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ATRIBUICAO:{
      jj_consume_token(ATRIBUICAO);
      Expressao();
      jj_consume_token(FIMESTRUTURA);
      break;
      }
    case ABRIRFUNC:{
      jj_consume_token(ABRIRFUNC);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TAMANHO:
      case TOPO:
      case PILHA_VAZIA:
      case TRUE:
      case FALSE:
      case ABRIREXP:
      case ABRIRFUNC:
      case LITERAL_STRING:
      case CONSTANTE_INT:
      case CONSTANTE_FLOAT:
      case IDENTIFICADOR:{
        ListaExpressoes();
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        ;
      }
      jj_consume_token(FECHARFUNC);
      jj_consume_token(FIMESTRUTURA);
      break;
      }
    case ADICIONAR:{
      jj_consume_token(ADICIONAR);
      Expressao();
      jj_consume_token(FIMESTRUTURA);
      break;
      }
    case REMOVER:{
      jj_consume_token(REMOVER);
      jj_consume_token(ABRIREXP);
      Expressao();
      jj_consume_token(FECHAREXP);
      jj_consume_token(FIMESTRUTURA);
      break;
      }
    case EMPILHAR:{
      jj_consume_token(EMPILHAR);
      Expressao();
      jj_consume_token(FIMESTRUTURA);
      break;
      }
    case DESEMPILHAR:{
      jj_consume_token(DESEMPILHAR);
      jj_consume_token(FIMESTRUTURA);
      break;
      }
    case FIMESTRUTURA:
    case ABRIREXP:
    case SOMA:
    case SUBTRACAO:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ABRIREXP:{
        jj_consume_token(ABRIREXP);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case TAMANHO:
        case TOPO:
        case PILHA_VAZIA:
        case TRUE:
        case FALSE:
        case ABRIREXP:
        case ABRIRFUNC:
        case LITERAL_STRING:
        case CONSTANTE_INT:
        case CONSTANTE_FLOAT:
        case IDENTIFICADOR:{
          ListaExpressoes();
          break;
          }
        default:
          jj_la1[4] = jj_gen;
          ;
        }
        jj_consume_token(FECHAREXP);
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        ;
      }
      sufixoExpressao();
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void sufixoExpressao() throws ParseException {
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SOMA:
      case SUBTRACAO:{
        ;
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        break label_2;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SOMA:{
        jj_consume_token(SOMA);
        break;
        }
      case SUBTRACAO:{
        jj_consume_token(SUBTRACAO);
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      fator();
    }
    jj_consume_token(FIMESTRUTURA);
}

/* ===================================================== */
  static final public 
void declaraVariavel() throws ParseException {
    tipoDado();
    ListaIdentificadores();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ATRIBUICAO:{
      jj_consume_token(ATRIBUICAO);
      ListaExpressoes();
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      ;
    }
    jj_consume_token(FIMESTRUTURA);
}

  static final public void tipoDado() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT:{
      jj_consume_token(INT);
      break;
      }
    case FLOAT:{
      jj_consume_token(FLOAT);
      break;
      }
    case STRING:{
      jj_consume_token(STRING);
      break;
      }
    case BOOL:{
      jj_consume_token(BOOL);
      break;
      }
    case LISTA:{
      tipoLista();
      break;
      }
    case PILHA:{
      tipoPilha();
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void ListaIdentificadores() throws ParseException {
    jj_consume_token(IDENTIFICADOR);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VIRGULA:{
        ;
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        break label_3;
      }
      jj_consume_token(VIRGULA);
      jj_consume_token(IDENTIFICADOR);
    }
}

  static final public void ListaExpressoes() throws ParseException {
    Expressao();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VIRGULA:{
        ;
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        break label_4;
      }
      jj_consume_token(VIRGULA);
      Expressao();
    }
}

  static final public void Expressao() throws ParseException {
    fator();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SOMA:
      case SUBTRACAO:{
        ;
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        break label_5;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SOMA:{
        jj_consume_token(SOMA);
        break;
        }
      case SUBTRACAO:{
        jj_consume_token(SUBTRACAO);
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      fator();
    }
}

  static final public void fator() throws ParseException {
    termo();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULTIPLICACAO:
      case DIVISAO:{
        ;
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        break label_6;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULTIPLICACAO:{
        jj_consume_token(MULTIPLICACAO);
        break;
        }
      case DIVISAO:{
        jj_consume_token(DIVISAO);
        break;
        }
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      termo();
    }
}

/* ========== TERMO REFATORADO (SEM LOOKAHEAD) ========== */
  static final public void termo() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFICADOR:{
      jj_consume_token(IDENTIFICADOR);
      termoIdentificadorSufixo();
      break;
      }
    case CONSTANTE_INT:{
      jj_consume_token(CONSTANTE_INT);
      break;
      }
    case CONSTANTE_FLOAT:{
      jj_consume_token(CONSTANTE_FLOAT);
      break;
      }
    case LITERAL_STRING:{
      jj_consume_token(LITERAL_STRING);
      break;
      }
    case TRUE:{
      jj_consume_token(TRUE);
      break;
      }
    case FALSE:{
      jj_consume_token(FALSE);
      break;
      }
    case TAMANHO:{
      jj_consume_token(TAMANHO);
      jj_consume_token(IDENTIFICADOR);
      break;
      }
    case ABRIREXP:{
      inicializacaoLista();
      break;
      }
    case TOPO:{
      jj_consume_token(TOPO);
      jj_consume_token(IDENTIFICADOR);
      break;
      }
    case PILHA_VAZIA:{
      jj_consume_token(PILHA_VAZIA);
      jj_consume_token(IDENTIFICADOR);
      break;
      }
    case ABRIRFUNC:{
      jj_consume_token(ABRIRFUNC);
      Expressao();
      jj_consume_token(FECHARFUNC);
      break;
      }
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

/*
 * Esta produção resolve a ambiguidade entre chamada de função
 * e acesso a variável/array ao utilizar 1 token lookahead
 */
  static final public void termoIdentificadorSufixo() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ABRIRFUNC:{
      jj_consume_token(ABRIRFUNC);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TAMANHO:
      case TOPO:
      case PILHA_VAZIA:
      case TRUE:
      case FALSE:
      case ABRIREXP:
      case ABRIRFUNC:
      case LITERAL_STRING:
      case CONSTANTE_INT:
      case CONSTANTE_FLOAT:
      case IDENTIFICADOR:{
        ListaExpressoes();
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        ;
      }
      jj_consume_token(FECHARFUNC);
      break;
      }
    default:
      jj_la1[21] = jj_gen;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ABRIREXP:{
        jj_consume_token(ABRIREXP);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case TAMANHO:
        case TOPO:
        case PILHA_VAZIA:
        case TRUE:
        case FALSE:
        case ABRIREXP:
        case ABRIRFUNC:
        case LITERAL_STRING:
        case CONSTANTE_INT:
        case CONSTANTE_FLOAT:
        case IDENTIFICADOR:{
          ListaExpressoes();
          break;
          }
        default:
          jj_la1[19] = jj_gen;
          ;
        }
        jj_consume_token(FECHAREXP);
        break;
        }
      default:
        jj_la1[20] = jj_gen;
        ;
      }
    }
}

/* ===================================================== */
  static final public 
void operadorLogico() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case OPDIF:{
      jj_consume_token(OPDIF);
      break;
      }
    case OPIGUAL:{
      jj_consume_token(OPIGUAL);
      break;
      }
    case OPMAIOR:{
      jj_consume_token(OPMAIOR);
      break;
      }
    case OPMENOR:{
      jj_consume_token(OPMENOR);
      break;
      }
    case OPMAIORIGUAL:{
      jj_consume_token(OPMAIORIGUAL);
      break;
      }
    case OPMENORIGUAL:{
      jj_consume_token(OPMENORIGUAL);
      break;
      }
    case OPAND:{
      jj_consume_token(OPAND);
      break;
      }
    case OPOR:{
      jj_consume_token(OPOR);
      break;
      }
    default:
      jj_la1[22] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void expressaoLogica() throws ParseException {
    Expressao();
    operadorLogico();
    Expressao();
}

  static final public void expressaoCondicional() throws ParseException {
    condicao();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SENAO:{
      jj_consume_token(SENAO);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CONDICIONAL:{
        condicao();
        break;
        }
      case ABREBLOCO:{
        jj_consume_token(ABREBLOCO);
        bloco();
        jj_consume_token(FECHABLOCO);
        break;
        }
      default:
        jj_la1[23] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[24] = jj_gen;
      ;
    }
}

  static final public void condicao() throws ParseException {
    jj_consume_token(CONDICIONAL);
    jj_consume_token(ABRIREXP);
    expressaoLogica();
    jj_consume_token(FECHAREXP);
    jj_consume_token(ABREBLOCO);
    bloco();
    jj_consume_token(FECHABLOCO);
}

  static final public void print() throws ParseException {
    jj_consume_token(PRINT);
    ListaExpressoes();
    jj_consume_token(FIMESTRUTURA);
}

  static final public void scan() throws ParseException {
    jj_consume_token(SCAN);
    jj_consume_token(IDENTIFICADOR);
    jj_consume_token(FIMESTRUTURA);
}

  static final public void whileLoop() throws ParseException {
    jj_consume_token(WHILE);
    jj_consume_token(ABRIREXP);
    expressaoLogica();
    jj_consume_token(FECHAREXP);
    jj_consume_token(ABREBLOCO);
    bloco();
    jj_consume_token(FECHABLOCO);
}

  static final public void forLoop() throws ParseException {
    jj_consume_token(FOR);
    jj_consume_token(ABRIREXP);
    atribuicaoFor();
    jj_consume_token(SEPARADOR);
    expressaoLogica();
    jj_consume_token(SEPARADOR);
    atribuicaoFor();
    jj_consume_token(FECHAREXP);
    jj_consume_token(ABREBLOCO);
    bloco();
    jj_consume_token(FECHABLOCO);
}

  static final public void atribuicaoFor() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LISTA:
    case PILHA:
    case INT:
    case FLOAT:
    case STRING:
    case BOOL:{
      tipoDado();
      break;
      }
    default:
      jj_la1[25] = jj_gen;
      ;
    }
    jj_consume_token(IDENTIFICADOR);
    jj_consume_token(ATRIBUICAO);
    Expressao();
}

  static final public void declaraFuncao() throws ParseException {
    jj_consume_token(FUNCAO);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LISTA:
    case PILHA:
    case INT:
    case FLOAT:
    case STRING:
    case BOOL:{
      tipoDado();
      break;
      }
    default:
      jj_la1[26] = jj_gen;
      ;
    }
    jj_consume_token(IDENTIFICADOR);
    jj_consume_token(ABRIRFUNC);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LISTA:
    case PILHA:
    case INT:
    case FLOAT:
    case STRING:
    case BOOL:{
      listaParametros();
      break;
      }
    default:
      jj_la1[27] = jj_gen;
      ;
    }
    jj_consume_token(FECHARFUNC);
    jj_consume_token(ABREBLOCO);
    bloco();
    jj_consume_token(FECHABLOCO);
}

  static final public void listaParametros() throws ParseException {
    parametro();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VIRGULA:{
        ;
        break;
        }
      default:
        jj_la1[28] = jj_gen;
        break label_7;
      }
      jj_consume_token(VIRGULA);
      parametro();
    }
}

  static final public void parametro() throws ParseException {
    tipoDado();
    jj_consume_token(IDENTIFICADOR);
}

  static final public void retorno() throws ParseException {
    jj_consume_token(RETURN);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TAMANHO:
    case TOPO:
    case PILHA_VAZIA:
    case TRUE:
    case FALSE:
    case ABRIREXP:
    case ABRIRFUNC:
    case LITERAL_STRING:
    case CONSTANTE_INT:
    case CONSTANTE_FLOAT:
    case IDENTIFICADOR:{
      Expressao();
      break;
      }
    default:
      jj_la1[29] = jj_gen;
      ;
    }
    jj_consume_token(FIMESTRUTURA);
}

  static final public void tipoLista() throws ParseException {
    jj_consume_token(LISTA);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT:{
      jj_consume_token(INT);
      break;
      }
    case FLOAT:{
      jj_consume_token(FLOAT);
      break;
      }
    case STRING:{
      jj_consume_token(STRING);
      break;
      }
    case BOOL:{
      jj_consume_token(BOOL);
      break;
      }
    default:
      jj_la1[30] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void inicializacaoLista() throws ParseException {
    jj_consume_token(ABRIREXP);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TAMANHO:
    case TOPO:
    case PILHA_VAZIA:
    case TRUE:
    case FALSE:
    case ABRIREXP:
    case ABRIRFUNC:
    case LITERAL_STRING:
    case CONSTANTE_INT:
    case CONSTANTE_FLOAT:
    case IDENTIFICADOR:{
      ListaExpressoes();
      break;
      }
    default:
      jj_la1[31] = jj_gen;
      ;
    }
    jj_consume_token(FECHAREXP);
}

  static final public void tipoPilha() throws ParseException {
    jj_consume_token(PILHA);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT:{
      jj_consume_token(INT);
      break;
      }
    case FLOAT:{
      jj_consume_token(FLOAT);
      break;
      }
    case STRING:{
      jj_consume_token(STRING);
      break;
      }
    case BOOL:{
      jj_consume_token(BOOL);
      break;
      }
    default:
      jj_la1[32] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public BrCompilerTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[33];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x1e022de0,0x1e022de0,0x1e0229e0,0x60310000,0x60310000,0x0,0x800cc000,0x0,0x0,0x80000000,0x1e022000,0x1000,0x1000,0x0,0x0,0x0,0x0,0x60310000,0x60310000,0x60310000,0x0,0x0,0x0,0x800000,0x0,0x1e022000,0x1e022000,0x1e022000,0x1000,0x60310000,0x1e000000,0x60310000,0x1e000000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x402,0x402,0x402,0x7a8,0x7a8,0x8,0x3029,0x3000,0x3000,0x0,0x0,0x0,0x0,0x3000,0x3000,0xc000,0xc000,0x7a8,0x7a8,0x7a8,0x8,0x20,0xff0000,0x2,0x4,0x0,0x0,0x0,0x0,0x7a8,0x0,0x7a8,0x0,};
	}

  /** Constructor with InputStream. */
  public BrCompiler(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public BrCompiler(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new BrCompilerTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 33; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 33; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public BrCompiler(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new BrCompilerTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 33; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new BrCompilerTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 33; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public BrCompiler(BrCompilerTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 33; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(BrCompilerTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 33; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[56];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 33; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 56; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

} //compilador

