/* Generated By:JavaCC: Do not edit this line. BrCompilerConstants.java */
package compiler;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BrCompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIOPROG = 5;
  /** RegularExpression Id. */
  int ABREBLOCO = 6;
  /** RegularExpression Id. */
  int FECHABLOCO = 7;
  /** RegularExpression Id. */
  int INT = 8;
  /** RegularExpression Id. */
  int FLOAT = 9;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int BOOL = 11;
  /** RegularExpression Id. */
  int ATRIBUICAO = 12;
  /** RegularExpression Id. */
  int FIMESTRUTURA = 13;
  /** RegularExpression Id. */
  int CONDICIONAL = 14;
  /** RegularExpression Id. */
  int ABRIREXP = 15;
  /** RegularExpression Id. */
  int FECHAREXP = 16;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 17;
  /** RegularExpression Id. */
  int SOMA = 18;
  /** RegularExpression Id. */
  int SUBTRACAO = 19;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 20;
  /** RegularExpression Id. */
  int DIVISAO = 21;
  /** RegularExpression Id. */
  int OPMAIOR = 22;
  /** RegularExpression Id. */
  int OPIGUAL = 23;
  /** RegularExpression Id. */
  int OPMENOR = 24;
  /** RegularExpression Id. */
  int OPDIF = 25;
  /** RegularExpression Id. */
  int CONSTANTE = 26;
  /** RegularExpression Id. */
  int DIGITO = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"gambiarra\"",
    "\"abre-te-sezamo\"",
    "\"fecha-te-sezamo\"",
    "\"stonks\"",
    "\"fiado\"",
    "\"textao\"",
    "\"eh-migue\"",
    "\"receba\"",
    "\"br\"",
    "\"sepa\"",
    "\"[\"",
    "\"]\"",
    "<IDENTIFICADOR>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\">\"",
    "\"==\"",
    "\"<\"",
    "\"!=\"",
    "<CONSTANTE>",
    "<DIGITO>",
    "\",\"",
    "\"(\"",
    "\")\"",
  };

}
