/* Generated By:JavaCC: Do not edit this line. BrCompilerConstants.java */
package compiler;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BrCompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PRINT = 5;
  /** RegularExpression Id. */
  int SCAN = 6;
  /** RegularExpression Id. */
  int FOR = 7;
  /** RegularExpression Id. */
  int WHILE = 8;
  /** RegularExpression Id. */
  int SEPARADOR = 9;
  /** RegularExpression Id. */
  int FUNCAO = 10;
  /** RegularExpression Id. */
  int RETURN = 11;
  /** RegularExpression Id. */
  int VIRGULA = 12;
  /** RegularExpression Id. */
  int LISTA = 13;
  /** RegularExpression Id. */
  int ADICIONAR = 14;
  /** RegularExpression Id. */
  int REMOVER = 15;
  /** RegularExpression Id. */
  int TAMANHO = 16;
  /** RegularExpression Id. */
  int INICIOPROG = 17;
  /** RegularExpression Id. */
  int ABREBLOCO = 18;
  /** RegularExpression Id. */
  int FECHABLOCO = 19;
  /** RegularExpression Id. */
  int INT = 20;
  /** RegularExpression Id. */
  int FLOAT = 21;
  /** RegularExpression Id. */
  int STRING = 22;
  /** RegularExpression Id. */
  int BOOL = 23;
  /** RegularExpression Id. */
  int TRUE = 24;
  /** RegularExpression Id. */
  int FALSE = 25;
  /** RegularExpression Id. */
  int ATRIBUICAO = 26;
  /** RegularExpression Id. */
  int FIMESTRUTURA = 27;
  /** RegularExpression Id. */
  int CONDICIONAL = 28;
  /** RegularExpression Id. */
  int SENAO = 29;
  /** RegularExpression Id. */
  int ABRIREXP = 30;
  /** RegularExpression Id. */
  int FECHAREXP = 31;
  /** RegularExpression Id. */
  int ABRIRFUNC = 32;
  /** RegularExpression Id. */
  int FECHARFUNC = 33;
  /** RegularExpression Id. */
  int LITERAL_STRING = 34;
  /** RegularExpression Id. */
  int CONSTANTE_INT = 35;
  /** RegularExpression Id. */
  int CONSTANTE_FLOAT = 36;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 37;
  /** RegularExpression Id. */
  int DIGITO = 38;
  /** RegularExpression Id. */
  int SOMA = 39;
  /** RegularExpression Id. */
  int SUBTRACAO = 40;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 41;
  /** RegularExpression Id. */
  int DIVISAO = 42;
  /** RegularExpression Id. */
  int OPMAIOR = 43;
  /** RegularExpression Id. */
  int OPIGUAL = 44;
  /** RegularExpression Id. */
  int OPMENOR = 45;
  /** RegularExpression Id. */
  int OPDIF = 46;
  /** RegularExpression Id. */
  int OPMAIORIGUAL = 47;
  /** RegularExpression Id. */
  int OPMENORIGUAL = 48;
  /** RegularExpression Id. */
  int OPAND = 49;
  /** RegularExpression Id. */
  int OPOR = 50;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"printa\"",
    "\"papa-entrada\"",
    "\"pet\"",
    "\"repet\"",
    "\";\"",
    "\"vai-filhao\"",
    "\"devolva\"",
    "\",\"",
    "\"tropa-do-gordao\"",
    "\"recrutar\"",
    "\"expulsar\"",
    "\"tamanho\"",
    "\"gambiarra\"",
    "\"abre-te-sezamo\"",
    "\"fecha-te-sezamo\"",
    "\"stonks\"",
    "\"fiado\"",
    "\"textao\"",
    "\"eh-migue\"",
    "\"sim\"",
    "\"nao\"",
    "\"receba\"",
    "\"br\"",
    "\"sepa\"",
    "\"da-teus-pulo\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "<LITERAL_STRING>",
    "<CONSTANTE_INT>",
    "<CONSTANTE_FLOAT>",
    "<IDENTIFICADOR>",
    "<DIGITO>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\">\"",
    "\"==\"",
    "\"<\"",
    "\"!=\"",
    "\" >=\"",
    "\"<=\"",
    "\"&&\"",
    "\"|\"",
  };

}
